import Image from "next/image";
import Link from "next/link";
import { AnimatedSection } from "@/components/AnimatedSection";
import { GlowCard } from "@/components/ui/GlowCard";
import { GlowButton } from "@/components/ui/GlowButton";

const pillars = [
  {
    title: "Social Storytelling",
    description: "We pair campus reporters with digital producers to package stories that trend across TikTok, Instagram, X, and Facebook.",
    detail: "Campaign playbooks, copy decks, and media templates are shared with presenters weekly.",
    icon: "https://res.cloudinary.com/demo/image/upload/v1720000000/glowfm/pillar-social.jpg"
  },
  {
    title: "On-Air Innovation",
    description: "Glow FM fuses live radio with interactive livestreams, letting audiences vote, react, and buy straight from broadcasts.",
    detail: "Analytics dashboards highlight which segments drive the highest engagement for each platform.",
    icon: "https://res.cloudinary.com/demo/image/upload/v1720000000/glowfm/pillar-onair.jpg"
  },
  {
    title: "Community Impact",
    description: "From the Ember Challenge to campus outreach, we reward listeners who uplift local culture and businesses.",
    detail: "Scholarship drives, hustler spotlights, and partnership takeovers are coordinated every quarter.",
    icon: "https://res.cloudinary.com/demo/image/upload/v1720000000/glowfm/pillar-community.jpg"
  }
];

const teamHighlights = [
  { label: "12", text: "Social editors scheduling content across five networks daily." },
  { label: "38", text: "Volunteer campus correspondents filing stories from three states." },
  { label: "250K", text: "Combined weekly impressions generated by Glow FM campaigns." }
];

export default function AboutPage() {
  return (
    <div className="space-y-16">
      <AnimatedSection className="rounded-3xl bg-glow-hero p-8 text-white shadow-glow-emphasis">
        <div className="grid gap-10 md:grid-cols-[1.4fr,1fr] md:items-center">
          <div className="space-y-6">
            <span className="inline-flex items-center rounded-full bg-white/10 px-4 py-1 text-xs uppercase tracking-[0.3em] text-white/80">
              About Glow 99.1 FM
            </span>
            <h1 className="text-4xl font-bold md:text-5xl">The Station Amplifying Campus Culture</h1>
            <p className="max-w-2xl text-base text-white/80 md:text-lg">
              Glow FM is a youth-first station broadcasting from Abuja, Nigeria. Our social media team engineers campaigns that merge live radio energy with digital storytelling, delivering measurable growth for artists, entrepreneurs, and community builders.
            </p>
            <GlowButton size="lg" variant="accent" className="uppercase tracking-[0.3em]" asChild>
              <Link href="/advertisement">Learn about our partnerships</Link>
            </GlowButton>
          </div>
          <div className="relative hidden h-full min-h-[280px] rounded-3xl border border-white/15 bg-black/20 shadow-2xl md:block">
            <Image
              src="https://res.cloudinary.com/demo/image/upload/v1720000000/glowfm/about-team.jpg"
              alt="Glow FM social media team collaborating"
              fill
              className="object-cover"
            />
          </div>
        </div>
      </AnimatedSection>

      <AnimatedSection className="space-y-8">
        <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
          <div>
            <h2 className="text-3xl font-semibold">What Drives Us</h2>
            <p className="text-sm text-[var(--foreground)]/70 dark:text-white/70">
              Three pillars guide our projects, campaigns, and partnerships.
            </p>
          </div>
        </div>
        <div className="grid gap-6 md:grid-cols-3">
          {pillars.map((pillar) => (
            <GlowCard key={pillar.title} title={pillar.title}>
              <div className="space-y-4">
                <div className="relative h-36 overflow-hidden rounded-2xl border border-white/10">
                  <Image src={pillar.icon} alt={pillar.title} fill className="object-cover" sizes="(max-width:768px) 100vw, 320px" />
                </div>
                <p className="text-sm text-[var(--foreground)]/80 dark:text-white/80">{pillar.description}</p>
                <p className="text-xs text-[var(--foreground)]/60 dark:text-white/60">{pillar.detail}</p>
              </div>
            </GlowCard>
          ))}
        </div>
      </AnimatedSection>

      <AnimatedSection className="grid gap-6 lg:grid-cols-[1.2fr,1fr]">
        <GlowCard title="The Team Behind the Glow" description="Cross-functional storytellers" headerClassName="bg-gradient-to-r from-glow-secondary to-glow-primary" className="shadow-glow-emphasis">
          <p className="text-sm text-[var(--foreground)]/80 dark:text-white/80">
            Producers, presenters, graphic artists, and analysts collaborate daily to keep Glow FM buzzing online and on-air. We script campaigns, design graphics, produce short-form video, and monitor dashboards around the clock.
          </p>
          <ul className="mt-4 space-y-3 text-sm">
            {teamHighlights.map((item) => (
              <li key={item.label} className="flex items-start gap-3">
                <span className="text-3xl font-semibold text-glow-accent">{item.label}</span>
                <span>{item.text}</span>
              </li>
            ))}
          </ul>
        </GlowCard>
        <GlowCard title="How to Collaborate" description="Partner with Glow FM" className="shadow-glow-soft">
          <p className="text-sm text-[var(--foreground)]/80 dark:text-white/80">
            We partner with brands, student unions, NGOs, and creative collectives. Choose a promo slot, co-produce an event, or integrate your message into our digital campaigns.
          </p>
          <ul className="mt-4 space-y-2 text-xs uppercase tracking-[0.35em] text-glow-secondary">
            <li>Influencer takeovers</li>
            <li>Sponsored segment scripting</li>
            <li>Performance reporting</li>
          </ul>
          <GlowButton asChild size="sm" variant="ghost" className="mt-6">
            <a href="/advertisement">View advertising options</a>
          </GlowButton>
        </GlowCard>
      </AnimatedSection>
    </div>
  );
}



